---
all:
  children:
    ipa_servers:
      hosts:
        ipa01:
          ansible_host: 192.0.2.10
          ipa_role: primary
        ipa02:
          ansible_host: 192.0.2.11
          ipa_role: replica
